export const LOGIN = 'LOGIN';
export const SAVE_FAVORITES_CHARACTERS = 'SAVE_FAVORITES_CHARACTERS';
export const GET_FAVORITES_CHARACTERS = 'GET_FAVORITES_CHARACTERS';
export const GET_CHARACTERS = 'GET_CHARACTERS';
export const GET_SORTED_FILMS_LIST = 'GET_SORTED_FILMS_LIST';